### ISSUE TITLE
Error for view files with no dimensions

### ISSUE THREAD

**Issue by kning** [spectacles-ci/lkmlstyle#19]
I have a skeleton view file with no dimensions in it that looks like this:

```
# /_standard/buildings.layer.lkml
include: "/_base/buildings.view.lkml"

view: +buildings {}
```

The idea here is that in the future, refinements to this view should be done in this file and not by editing the `_base` files that are machine generated by Looker.

I get the following output from linting on the command line:
```
(env) ➜  findigs-looker git:(master) ✗ lkmlstyle _standard/buildings.layer.lkml
──────────────────────────────────────────────────────────────────────────────────────── buildings.layer.lkml ────────────────────────────────────────────────────────────────────────────────────────

[V100] View name not in snake case
_standard/buildings.layer.lkml:3
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 3    >| view: +buildings {}
 4     |
lkmlstyle encountered an unexpected issue.

We're not sure what happened, but you can see the traceback below.

For support, please open an issue at https://github.com/spectacles-ci/lkmlstyle/

Traceback (most recent call last):
  File "/Users/findigs/code/findigs-looker/env/bin/lkmlstyle", line 8, in <module>
    sys.exit(main())
  File "/Users/findigs/code/findigs-looker/env/lib/python3.10/site-packages/lkmlstyle/cli.py", line 256, in main
    check_style(args)
  File "/Users/findigs/code/findigs-looker/env/lib/python3.10/site-packages/lkmlstyle/cli.py", line 170, in check_style
    f" [dim]{n:<4}[/dim]  | [dim]{lines[n - 1]}[/dim]",
IndexError: list index out of range
```
I think the problem is this line is assuming that each view has at least one dimension, which is maybe true 95% of the time, but not always.

**Comment by the-kevin-kong** [comment]
Likewise, receiving this same error for a barebone explore, which may be a more common use-case.

```
include: "/views/utils/snowflake_task_history.view.lkml"
explore: snowflake_task_history {}
```

Confirmed that adding any parameter fixes the issue:

```
include: "/views/utils/snowflake_task_history.view.lkml"
explore: snowflake_task_history {
    label: "TEST"
}
```

**Comment by joshtemple** [comment]
I can't reproduce with the the current version on `master`, so it should be resolved. However, I won't be cutting any new releases until `0.1.0`, which should be released by the end of the month.
